RealState-Site/Site/Areas/Customer/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using IoC.Core.Entities;
using IoC.Core.ServiceManagement;
using IoC.Core.ServiceManagement.ManagerCatalogues;

namespace Site.Areas.Customer.Models
{
    public class HomeViewModel
    {

        public IList<Catalogues> Catalogues { get; set; }
        public IList<SlideHome> SlideHomes { get; set; }


        public HomeViewModel() { }
        public HomeViewModel(IList<Catalogues> _CataLogues, IList<SlideHome> _SlideHome) 
        {
            this.Catalogues = _CataLogues;
            this.SlideHomes = _SlideHome;
        }

    }
}

RealState-Site/Site/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IoC.Core.Entities;
using IoC.Core.ServiceManagement.ManagerSlideHome;
using IoC.Core.ServiceManagement.ManagerCatalogues;
using Site.Areas.Customer.Models;

namespace Site.Areas.Customer.Controllers
{
    public class HomeController : Controller
    {
        private ICatalogueService _catalogueService;
        private ISlideHomeService _slidehomeService;

        public HomeController(ICatalogueService catalogueService, ISlideHomeService slidehomeService)
        {
            this._catalogueService = catalogueService;
            this._slidehomeService = slidehomeService;
        }

        public ActionResult Index()
        {
            var cataList = _catalogueService.GetThreeCatalogues();
            var slideList = _slidehomeService.GetSlideHomes();
            if (cataList.Count() == 0)
            {
                return View("NoContent");
            }
            HomeViewModel hv = new HomeViewModel(cataList,slideList);
            return View(hv);
            
        }

        
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RealState-Site/Site/Areas/Mobile/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using IoC.Core.ServiceManagement.ManagerProduct;
using IoC.Core.ServiceManagement.ManagerFileStore;
using IoC.Core.ServiceManagement.ManagerProductOwner;
using IoC.Core.ServiceManagement.ManagerCatalogues;
using IoC.Core.Entities;
using Site.Areas.Mobile.Models;
using PagedList;
using IoC.Core.Pagination;

namespace Site.Areas.Mobile.Controllers
{
    public class ProductController : ApiController
    {
        //private IProductService _productService;
        //private IFileStoreService _filestoreService;
        //private IProductOwnerService _productownerService;
        //private ICatalogueService _catalogueService;
        /// <summary>
        /// 
        /// </summary>
        /// <param name="productService"></param>

        //public ProductController(ICatalogueService catalogueService, IProductService productService, IFileStoreService filestoreService, IProductOwnerService productownerService)
        //{
        //    this._productService = productService;
        //    this._filestoreService = filestoreService;
        //    this._productownerService = productownerService;
        //    this._catalogueService = catalogueService;
        //}

        // GET: /Product/   
        
        //public Product Get(long id)
        //{            
        //    var product = _productService.GetProduct(id);
        //    if (product == null)
        //    {
        //        return null;
        //    }
        //    //ProductViewModel productModel = new ProductViewModel(product);
        //    return product;
            
        //}
        //[HttpGet]
        //public Product GetHello()
        //{
        //    Product product = new Product();
        //    product.Name = "Nhà Riêng";
        //    return product;
        //}
        //public Product GetItem()
        //{
        //    Product model = new Product();
        //    model.Name = "Nhà Riêng";
        //    model.BedRoom = 5;
        //    model.BathRoom = 3;
        //    model.WC = 3;
        //    model.Width = 5;
        //    model.Hight = 20;
        //    model.Price = 15848;            
        //    model.EAH = "Khu dân trí cao, an ninh, thuận tiện trường, chợ, bệnh viên, phường, quận";
        //    model.Direction = "Đông Nam";

        //    return model;
        //}
        [System.Web.Http.AcceptVerbs("GET", "POST")]
        [System.Web.Http.HttpGet]
        public ProductViewModel GetItem()
        {
            ProductViewModel model = new ProductViewModel();
            model.ProductId = 5;
            model.Name = "Nhà Riêng";
            model.BedRoom = 5;
            model.BathRoom = 3;
            model.WC = 3;
            model.Width = 5;
            model.Hight = 20;
            model.Price = 15848;            
            model.EAH = "Khu dân trí cao, an ninh, thuận tiện trường, chợ, bệnh viên, phường, quận";
            model.Direction = "Đông Nam";

            return model;
        }


        [System.Web.Http.AcceptVerbs("GET", "POST")]
        [System.Web.Http.HttpGet]
        public string Hello()
        {
            return "Hello, This is a product";
        }


        [System.Web.Http.AcceptVerbs("GET", "POST")]
        [System.Web.Http.HttpGet]
        public string Hello(string name)
        {
            return "Hello, " + name + " This is a product";
        }
    }
}

RealState-Site/Site/Areas/Customer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RealState-Site/Site/Areas/Customer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<address>     
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RealState-Site/Site/Areas/Customer/Views/Home/Index.cshtml
@model Site.Areas.Customer.Models.HomeViewModel
@{
    ViewBag.Title = "Home Page";
}

<style>    
        .carousel-inner > .item > img,
        .carousel-inner > .item > a > img {            
            width: 50%;
            margin: auto;
        }
</style>
<div class="container">
    <br />
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            @{var counter = 1;           
            foreach (var itemImage in Model.SlideHomes)
            {
                if (itemImage == Model.SlideHomes.FirstOrDefault())
                {
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                }
                else
                {
                    <li data-target="#myCarousel" data-slide-to="@counter"></li>
                }
                counter++;
            }
            }
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

            @foreach (var itemImage in Model.SlideHomes)
            {
                if (itemImage == Model.SlideHomes.FirstOrDefault())
                {
                    <div class="item active">
                        <img src="@Url.Content(itemImage.Image)" alt="Image" width="650px" height="150px" />
                    </div>
                }
                else
                {
                    <div class="item">
                        <img src="@Url.Content(itemImage.Image)" alt="Image" width="650px" height="150px" />
                    </div>
                }
            }
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<div class="row">
    @foreach(var item in Model.Catalogues)
    {
        <div class="col-md-4">
        <h2>@Html.DisplayFor(it => item.Name)</h2>
        <p>
            @Html.DisplayFor(it => item.Description)
        </p>
            <p>
                <a class="btn btn-default" href="@Url.Action("ProductList", "Product", new { id = item.CataloguesId })">Xem Chi Tiết &raquo;</a>                                
            </p>
        </div>
    }
   
</div>

RealState-Site/Site/Areas/Customer/Views/Home/NoContent.cshtml
@{
    ViewBag.Title = "Home page";
    Layout = null;

}
<center><strong>Dữ liệu chưa được khởi tạo</strong></center>