RealState-Site/Site/Areas/Customer/Controllers/CatalogueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IoC.Core.ServiceManagement.ManagerCatalogues;
using Site.Areas.Customer.Models;
using PagedList;


namespace Site.Areas.Customer.Controllers
{
    public class CatalogueController : Controller
    {
        private ICatalogueService _catalogueService;

        public CatalogueController(ICatalogueService catalogueService )
        {
            this._catalogueService = catalogueService;
        }


        //
        // GET: /Catalogue/
        public ActionResult Index()
        {
            IEnumerable<CatalogueViewModel> list = _catalogueService.GetCatalogues().Select(c => new CatalogueViewModel
            { 
                Name = c.Name,
                Description = c.Description
            });
            
            return View(list.ToList());            
        }

        public ActionResult CatalogueList()
        {
            IEnumerable<CatalogueViewModel> list = _catalogueService.GetCatalogues().Select(c => new CatalogueViewModel
            {
                CatalogueId = c.CataloguesId,
                Name = c.Name,
                Description = c.Description
            });
            if(list.Count() == 0)
            {
                return View("NoContent");
            }
            return View(list);
            
        }


        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
	}
}

RealState-Site/Site/Areas/Customer/Controllers/ProductOwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IoC.Core.Entities;
using IoC.Core.ServiceManagement.ManagerProductOwner;
using PagedList;
using Site.Areas.Customer.Models;
namespace Site.Areas.Customer.Controllers
{
    public class ProductOwnerController : BaseController
    {
        

        //
        // GET: /ProductOwner/

        private IProductOwnerService _productownerService;

        public ProductOwnerController(IProductOwnerService productownerService)
        {
            this._productownerService = productownerService;
        }
      
        public ActionResult Index(int page = 1, int pageSize = 3)
        {
            IEnumerable<ProductOwnerViewModel> listProductOwner = _productownerService.GetProductOwners().Select(p => new ProductOwnerViewModel
            {
                
                FirstName = p.FirstName,
                LastName = p.LastName,
                FullName = p.FirstName + " " + p.LastName
            });
            
            var model = new PagedList<ProductOwnerViewModel>(listProductOwner.ToList(), page, pageSize);
            //var model = listProductOwner.OrderBy(i => i.FullName).ToPagedList(page, pageSize);
            return View(model);
        }
	}
}

RealState-Site/Site/Areas/Customer/Views/Shared/_Layout.cshtml
@using Site.Areas.Customer.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    


    @RenderPage("~/Areas/Customer/Views/Shared/_LayoutHeader.cshtml")                                                   
    <div class="container body-content">        
        @RenderBody()       
    </div>
    @RenderPage("~/Areas/Customer/Views/Shared/_LayoutFooter.cshtml")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
      
    
</body>
</html>

RealState-Site/Site/Areas/Customer/Views/Shared/_LayoutFooter.cshtml
<hr />
<footer class="container-fluid text-center">
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
</footer>

RealState-Site/Site/Areas/Customer/Views/Shared/_LayoutHeader.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Product", "Index/1", "Product")</li>
                <li>@Html.ActionLink("User", "ItemList", "User")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                <!--Dropdown menu-->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Product
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Product 11", "Index/1", "Product")</li>
                        <li>@Html.ActionLink("Product 2", "Index/1", "Product")</li>
                        <li>@Html.ActionLink("Product 3", "Index/1", "Product")</li>
                    </ul>
                </li>

                <!--Dropdown Catalogue menu-->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Catalogues
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Catalogue 1", "Index", "Catalogue")</li>
                        <li>@Html.ActionLink("Catalogue 2", "Index", "Catalogue")</li>
                        <li>@Html.ActionLink("Catalogue 3", "Index", "Catalogue")</li>
                    </ul>
                </li>

                <!--Dropdown ProductOwner menu-->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        Product Owner
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("ProductOwner 1", "Index", "ProductOwner")</li>
                        <li>@Html.ActionLink("ProductOwner 2", "Index", "ProductOwner")</li>
                        <li>@Html.ActionLink("ProductOwner 3", "Index", "ProductOwner")</li>
                    </ul>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
                      
        </div>        
    </div>
</div> 
<div>
    You are here:@Html.MvcSiteMap().SiteMapPath()    
</div>

RealState-Site/Site/Areas/Customer/Views/Shared/_LayoutProduct.cshtml
@using Site.Areas.Customer.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    @RenderPage("~/Areas/Customer/Views/Shared/_LayoutHeader.cshtml")    
    <div class="container body-content">
        
        <div class="row">
            <!--Left side-->
            <div class="col-sm-3">
                @Html.Action("CatalogueList","Catalogue")                
            </div>

            <!--middle side-->
            <div class="col-sm-7">
                @RenderBody()
            </div>

            <!--right side-->
            <div class="col-sm-2">

            </div>
        </div>
    </div>
    @RenderPage("~/Areas/Customer/Views/Shared/_LayoutFooter.cshtml")

    @Scripts.Render("~/bundles/jquery")    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)   
    
</body>
</html>